### ISSUE TITLE
Add Rule to detect TODO's FIXME's and other type of comments

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#25]
Do we want to disable todos? no!

Suggestion from @ccjernigan 

> I managed to configure a regex for detekt (a similar static analysis tool for Kotlin code), that allows todos if they have an issue number associated with them. E.g. TODO [#123]: This doesn't correctly support LTR languages wouldn't trigger a failure but a plain TODO: This doesn't correctly support LTR languages would trigger a failure.
>
>
> Does SwiftLint support anything similar?

Things to do:
- Add rule to Swift lint .yml file to Detect that TODO's and FIXME's have a github issue associated  to them 

Example:

````
ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
      - 'TODO:'
    allowedPatterns: '\[[^\]]\d+\]'
````

- Document on SWIFTLINT.md
